# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *


# Create window class
class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")  #Window name
        MainWindow.resize(1400, 700)             #Window size
        self.setStyleSheet("background-color: '#59334b';")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        #sets the label channel name
        self.label = QtWidgets.QLabel(self.centralwidget)
        #sets the size of the label
        self.label.setGeometry(QtCore.QRect(700, 60, 200, 30))
        self.label.setStyleSheet("font-size:28px;color:white")
        #sets the font of the label
        font = QtGui.QFont()

        self.label.setFont(font)
        self.label.setObjectName("label")

        #set the label name
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1000, 60, 200, 30))
        self.label_2.setStyleSheet("font-size:28px;color:white")
        font = QtGui.QFont()

        self.label_2.setFont(font)
        self.label_2.setObjectName("label")

        #creates and sets size of  a pushbutton to join the channel
        self.joinButton = QtWidgets.QPushButton(self.centralwidget)
        self.joinButton.setGeometry(QtCore.QRect(700, 160, 93, 28))
        self.joinButton.setStyleSheet("background-color: gray")
        self.joinButton.setObjectName("joinButton")

        #creates and sets size of  a pushbutton to leave the channel
        self.leaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.leaveButton.setGeometry(QtCore.QRect(850, 160, 93, 28))
        self.leaveButton.setStyleSheet("background-color: gray")
        self.leaveButton.setObjectName("leaveButton")

        #sets the window to show incoming and outgoing vedio
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(650, 430, 300, 200))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")


        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(7)
        self.gridLayout.setObjectName("gridLayout")


        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 30, 600, 600))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")


        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")

        #creates and sets size of  a pushbutton to disable/enable vedio
        self.videoButton = QtWidgets.QPushButton(self.centralwidget)
        self.videoButton.setGeometry(QtCore.QRect(700, 205, 110, 30))
        self.videoButton.setCheckable(True)
        self.videoButton.setStyleSheet("background-color: gray")
        self.videoButton.setObjectName("videoButton")


        #creates and sets size of  a pushbutton to disable audio
        self.AudioButton = QtWidgets.QPushButton(self.centralwidget)
        self.AudioButton.setGeometry(QtCore.QRect(850, 205, 110, 30))
        self.AudioButton.setCheckable(True)
        self.AudioButton.setStyleSheet("background-color: gray")
        self.AudioButton.setObjectName("disableAudioButton")

        # creates and sets size of  a pushbutton to screen recording
        self.screenrecButton = QtWidgets.QPushButton(self.centralwidget)
        self.screenrecButton.setGeometry(QtCore.QRect(700, 300, 130, 28))
        self.screenrecButton.setStyleSheet("background-color: gray")
        self.screenrecButton.setObjectName("screenrecButton")

        self.declare = QtWidgets.QLabel(self.centralwidget)
        self.declare.setGeometry(QtCore.QRect(700, 340, 200, 50))
        self.declare.setStyleSheet("font-size:18px;color:gray")
        font = QtGui.QFont()

        self.declare.setFont(font)
        self.declare.setObjectName("declare")


        #sets label to take channel name as input
        self.channelEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.channelEdit.setGeometry(QtCore.QRect(700, 100, 240, 50))
        self.channelEdit.setStyleSheet("font-size:28px;color:white")
        self.channelEdit.setObjectName("channelEdit")

        # sets label to take name as input
        self.namelabel = QtWidgets.QLineEdit(self.centralwidget)
        self.namelabel.setGeometry(QtCore.QRect(1000, 100, 240, 50))
        self.namelabel.setStyleSheet("font-size:28px;color:white")
        self.namelabel.setObjectName("namelabel")

        MainWindow.setCentralWidget(self.centralwidget)
        # sets menubar
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        #sets statusbar
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        #sets the text area to display messages
        self.text_area = QPlainTextEdit(MainWindow)
        self.text_area.setGeometry(1000, 160, 320, 290)
        self.text_area.setFocusPolicy(Qt.NoFocus)
        self.text_area.setStyleSheet("font-size:20px;color:white")

        #sets the label to take message as input
        self.message_input = QLineEdit(MainWindow)
        self.message_input.setGeometry(1000, 470, 300, 70)
        self.message_input.setMaxLength(1000)  # max character length of a chat message
        self.message_input.setStyleSheet("font-size:24px;color:white")

        #creayes and sets size of a pushbutton to send messages
        self.sendButton = QtWidgets.QPushButton(self)
        self.sendButton.setGeometry(1302, 470, 50, 70)
        self.sendButton.setStyleSheet("background-color: gray")
        self.sendButton.setObjectName("sendButton")

        self.layout_1 = QVBoxLayout(self)
        self.layout_1.addWidget(self.text_area)
        self.layout_1.addWidget(self.message_input)


        self.retranslateUi(MainWindow)
        # Automatically connect signals to slots by their name
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        # Set window label
        MainWindow.setWindowTitle(_translate("MainWindow", "vedio call"))
        # Set label display text
        self.label.setText(_translate("MainWindow", "Channel Name:"))
        self.label_2.setText(_translate("MainWindow", "Name:"))
        # Set button display text
        self.joinButton.setText(_translate("MainWindow", "join"))
        self.leaveButton.setText(_translate("MainWindow", "leave"))
        self.videoButton.setText(_translate("MainWindow", "Turn Off Vedio"))
        self.AudioButton.setText(_translate("MainWindow", "Turn Off Audio"))
        self.screenrecButton.setText(_translate("MainWindow", "Screen Recording"))
        self.sendButton.setText(_translate("MainWindow", "Send"))


        #MainWindow.setWindowTitle(_translate("MainWindow", "chatapp"))
        # self.message_input.setText(_translate("chatMainwindow", "Message"))
        #self.sendButton.setText(_translate("MainWindow", "Send"))

        #self.label_2.setText(_translate("MainWindow", "AppId:"))




