# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from qtwidgets import Toggle

# Create window class
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")  #Window name
        MainWindow.resize(1000, 700)             #Window size
        self.setStyleSheet("background-color: '#59334b';")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        #sets the label
        self.label = QtWidgets.QLabel(self.centralwidget)
        #sets the size of the label
        self.label.setGeometry(QtCore.QRect(700, 60, 200, 30))
        self.label.setStyleSheet("font-size:28px;color:gray")
        #sets the font of the label
        font = QtGui.QFont()

        self.label.setFont(font)
        self.label.setObjectName("label")

        #creates and sets size of  a pushbutton to join the channel
        self.joinButton = QtWidgets.QPushButton(self.centralwidget)
        self.joinButton.setGeometry(QtCore.QRect(700, 160, 93, 28))
        self.joinButton.setStyleSheet("background-color: gray")
        self.joinButton.setObjectName("joinButton")

        #creates and sets size of  a pushbutton to leave the channel
        self.leaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.leaveButton.setGeometry(QtCore.QRect(850, 160, 93, 28))
        self.leaveButton.setStyleSheet("background-color: gray")
        self.leaveButton.setObjectName("leaveButton")

        #sets the window to show incoming and outgoing vedio
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(650, 430, 300, 200))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")


        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(7)
        self.gridLayout.setObjectName("gridLayout")


        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 30, 600, 600))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")


        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")

        #creates and sets size of  a pushbutton to disable/enable vedio
        self.videoButton = QtWidgets.QPushButton(self.centralwidget)
        self.videoButton.setGeometry(QtCore.QRect(700, 205, 60, 60))
        self.videoButton.setCheckable(True)
        self.videoButton.setStyleSheet("background-color: gray")
        self.videoButton.setObjectName("videoButton")


        #creates and sets size of  a pushbutton to disable audio
        self.AudioButton = QtWidgets.QPushButton(self.centralwidget)
        self.AudioButton.setGeometry(QtCore.QRect(850, 205, 60, 60))
        self.AudioButton.setCheckable(True)
        self.AudioButton.setStyleSheet("background-color: gray")
        self.AudioButton.setObjectName("disableAudioButton")


        self.screenrecButton = QtWidgets.QPushButton(self.centralwidget)
        self.screenrecButton.setGeometry(QtCore.QRect(700, 300, 130, 28))
        self.screenrecButton.setStyleSheet("background-color: gray")
        self.screenrecButton.setObjectName("screenrecButton")

        self.declare = QtWidgets.QLabel(self.centralwidget)
        self.declare.setGeometry(QtCore.QRect(700, 340, 200, 50))
        self.declare.setStyleSheet("font-size:18px;color:gray")
        font = QtGui.QFont()

        self.declare.setFont(font)
        self.declare.setObjectName("declare")


        #self.label_2 = QtWidgets.QLabel(self.centralwidget)
        #self.label_2.setGeometry(QtCore.QRect(540, 40, 111, 16))
        #font = QtGui.QFont()
        #self.label_2.setFont(font)
        #self.label_2.setObjectName("label_2")
        #self.appIdEdit = QtWidgets.QLineEdit(self.centralwidget)
        #self.appIdEdit.setGeometry(QtCore.QRect(540, 60, 231, 31))
        #self.appIdEdit.setObjectName("appIdEdit")

        #sets label to take channel name as input
        self.channelEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.channelEdit.setGeometry(QtCore.QRect(700, 100, 240, 50))
        self.channelEdit.setStyleSheet("font-size:28px;color:gray")
        self.channelEdit.setObjectName("channelEdit")

        MainWindow.setCentralWidget(self.centralwidget)
        # sets menubar
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        #sets statusbar
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        # Automatically connect signals to slots by their name
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        # Set window label
        MainWindow.setWindowTitle(_translate("vedio call", "vedio call"))
        # Set label display text
        self.label.setText(_translate("MainWindow", "Channel Name:"))
        # Set button display text
        self.joinButton.setText(_translate("MainWindow", "join"))
        self.leaveButton.setText(_translate("MainWindow", "leave"))
        self.videoButton.setStyleSheet("border-image : url('videoon.png');")
        self.AudioButton.setStyleSheet("border-image : url('mic.png');")
        self.screenrecButton.setText(_translate("MainWindow", "Screen Recording"))
        self.declare.setText(_translate("MainWindow", "Press ESC to stop \n Screen Recording ..."))
        #self.label_2.setText(_translate("MainWindow", "AppId:"))
